'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Job
    Public Property job_id As Integer
    Public Property jon_name As String

    Public Overridable Property Users As ICollection(Of User) = New HashSet(Of User)

End Class
